# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 610b9bcfc16ccc17595b20201946dbd519cbe215d6b5109f8065acdc442ef5c2151bbf6fcad9d10d3a4cece40757ba4e7a6eb11b8df53c1e6ae53caa0472b530

test:
  secret_key_base: 6095f8ab7b2049f4b59668983e0573a3064a9d672bff2169905d83d76b4f7d0504b85de3cdd24741ad8ef1cb67d6a5ffb61efa30bb082009d6d0fddc01339188

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
